<a href="https://colab.research.google.com/github/Paulina9555/03_feature_extraction/blob/main/03_feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Spis treści:
1. [Import bibliotek](#0)
2. [Załadowanie danych](#1)
3. [Utworzenie kopii danych](#2)
4. [Generowanie nowych zmiennych](#3)
5. [Dyskretyzacja zmiennej ciągłej](#4)
6. [Ekstrakcja cech](#5)

### <a name='0'></a> Import bibliotek

In [1]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

### <a name='1'></a> Załadowanie danych

In [3]:
def fetch_financial_data(company='AMZN'):
  """
  This function fetches stock market quotations.
  """
  import pandas_datareader.data as web
  return web.DataReader(name=company, data_source='stooq')

df_raw = fetch_financial_data()
df_raw.head()

               Open       High      Low   Close    Volume
Date
2025-05-02  191.435  192.88000  186.400  189.98  77903487
2025-05-01  190.630  191.80711  187.500  190.20  74265963
2025-04-30  182.170  185.05000  178.850  184.42  55176543
2025-04-29  183.990  188.01580  183.680  187.39  41667255
2025-04-28  190.105  190.22000  184.885  187.70  33224732

### <a name='2'></a> Utworzenie kopii danych

In [4]:
df = df_raw.copy()
df = df[:5]
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2025-05-02 to 2025-04-28
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    5 non-null      float64
 1   High    5 non-null      float64
 2   Low     5 non-null      float64
 3   Close   5 non-null      float64
 4   Volume  5 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 240.0 bytes

### <a name='3'></a> Generowanie nowych zmiennych

In [6]:
df['day'] = df.index.day
df['month'] = df.index.month
df['year'] = df.index.year
df

               Open       High      Low   Close    Volume  day  month  year
Date
2025-05-02  191.435  192.88000  186.400  189.98  77903487    2      5  2025
2025-05-01  190.630  191.80711  187.500  190.20  74265963    1      5  2025
2025-04-30  182.170  185.05000  178.850  184.42  55176543   30      4  2025
2025-04-29  183.990  188.01580  183.680  187.39  41667255   29      4  2025
2025-04-28  190.105  190.22000  184.885  187.70  33224732   28      4  2025

### <a name='4'></a> Dyskretyzacja zmiennej ciągłej

In [7]:
df = pd.DataFrame(data={'height' : [175., 178.5, 185., 191., 184.5, 183., 168.]})
df

   height
0   175.0
1   178.5
2   185.0
3   191.0
4   184.5
5   183.0
6   168.0

In [8]:
df['height_cat'] = pd.cut(x=df.height, bins=3)
df

   height          height_cat
0   175.0  (167.977, 175.667]
1   178.5  (175.667, 183.333]
2   185.0    (183.333, 191.0]
3   191.0    (183.333, 191.0]
4   184.5    (183.333, 191.0]
5   183.0  (175.667, 183.333]
6   168.0  (167.977, 175.667]

In [10]:
df['height_cat'] = pd.cut(x=df.height, bins=(160, 175, 180, 195))
df

   height  height_cat
0   175.0  (160, 175]
1   178.5  (175, 180]
2   185.0  (180, 195]
3   191.0  (180, 195]
4   184.5  (180, 195]
5   183.0  (180, 195]
6   168.0  (160, 175]

In [11]:
df['height_cat'] = pd.cut(x=df.height, bins=(160, 175, 180, 195), labels=['small', 'medium', 'high'])
df

   height height_cat
0   175.0      small
1   178.5     medium
2   185.0       high
3   191.0       high
4   184.5       high
5   183.0       high
6   168.0      small

In [12]:
pd.get_dummies(df, drop_first=True, prefix='height')

   height  height_medium  height_high
0   175.0          False        False
1   178.5           True        False
2   185.0          False         True
3   191.0          False         True
4   184.5          False         True
5   183.0          False         True
6   168.0          False        False

### <a name='5'></a> Ekstrakcja cech

In [13]:
df = pd.DataFrame(data={'lang': [['PL', 'ENG'],['GER', 'ENG', 'PL', 'FRA'],['RUS']]})
df

                  lang
0            [PL, ENG]
1  [GER, ENG, PL, FRA]
2                [RUS]

In [14]:
df['lang_number'] = df['lang'].apply(len)
df

                  lang  lang_number
0            [PL, ENG]            2
1  [GER, ENG, PL, FRA]            4
2                [RUS]            1

In [15]:
df['PL_flag'] = df['lang'].apply(lambda x: 1 if 'PL' in x else 0)
df

                  lang  lang_number  PL_flag
0            [PL, ENG]            2        1
1  [GER, ENG, PL, FRA]            4        1
2                [RUS]            1        0

In [16]:
df = pd.DataFrame(data={'website': ['wp.pl', 'onet.pl', 'google.com']})
df

      website
0       wp.pl
1     onet.pl
2  google.com

In [17]:
df.website.str.split('.', expand=True)

        0    1
0      wp   pl
1    onet   pl
2  google  com

In [20]:
new = df.website.str.split('.', expand = True)
df['portal'] = new[0]
df['extension'] = new[1]
df

      website  portal extension
0       wp.pl      wp        pl
1     onet.pl    onet        pl
2  google.com  google       com